# Generated by tools/release/homebrew/build-formula.py - do not edit by hand.
# The URLs point at the public mirror and the digests come from the release's
# checksums.txt (doc 08, "The Homebrew tap").
class Securechain < Formula
  desc "Supply-chain gate for your dependencies, as a single static binary"
  homepage "https://tuxcare.com/securechain"
  version "0.1.18"
  # The TuxCare License Agreement has no SPDX identifier; brew's symbol for that.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://securechain.tuxcare.com/get/v0.1.18/securechain-darwin-arm64"
      sha256 "0792ce394ffe14516222c8b31e6fcea3ed7ca0a00a60c4214bdaedcefcb36473"
    end
    on_intel do
      url "https://securechain.tuxcare.com/get/v0.1.18/securechain-darwin-amd64"
      sha256 "1c93afc2094ea3e8e0c4dea4b030e841c6b410cd42395c253f0395c447d2c1a2"
    end
  end

  on_linux do
    on_arm do
      url "https://securechain.tuxcare.com/get/v0.1.18/securechain-linux-arm64"
      sha256 "fed76ed90446565d6bd7315f041846d1a1963c4fc3a25d5ebaccbca6f56ba7d0"
    end
    on_intel do
      url "https://securechain.tuxcare.com/get/v0.1.18/securechain-linux-amd64"
      sha256 "5e2bafe285f821ef6256d8a0a335d39c5933a1cc564ed1e4de3d4ee3497fc831"
    end
  end

  def install
    bin.install Dir["securechain-*"].fetch(0) => "securechain"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/securechain version")
  end
end
