# Generated by tools/release/homebrew/build-formula.py - do not edit by hand.
# The URLs point at the public mirror and the digests come from the release's
# checksums.txt (doc 08, "The Homebrew tap").
class Securechain < Formula
  desc "Supply-chain gate for your dependencies, as a single static binary"
  homepage "https://tuxcare.com/securechain"
  version "0.1.15"
  # The TuxCare License Agreement has no SPDX identifier; brew's symbol for that.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://securechain.tuxcare.com/get/v0.1.15/securechain-darwin-arm64"
      sha256 "5c860c3be0127edeb5d40ee29877a1322b8e3db133f83f88ba2c372caa911a98"
    end
    on_intel do
      url "https://securechain.tuxcare.com/get/v0.1.15/securechain-darwin-amd64"
      sha256 "ce83212e4780737af39d04a175e966e23ebb28e9fb9ce39e973d562c6d71cac8"
    end
  end

  on_linux do
    on_arm do
      url "https://securechain.tuxcare.com/get/v0.1.15/securechain-linux-arm64"
      sha256 "bcdef35cbf1a02dd5a86aee8139a8cf7292456c7b849b9877f5c6baa13ce797b"
    end
    on_intel do
      url "https://securechain.tuxcare.com/get/v0.1.15/securechain-linux-amd64"
      sha256 "1b0ac36ec3f785a489a978ce615db03fdbb06c4af6046c4b04598e0ffdeb0a0f"
    end
  end

  def install
    bin.install Dir["securechain-*"].fetch(0) => "securechain"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/securechain version")
  end
end
