# Generated by tools/release/homebrew/build-formula.py - do not edit by hand.
# The URLs point at the public mirror and the digests come from the release's
# checksums.txt (doc 08, "The Homebrew tap").
class Securechain < Formula
  desc "Supply-chain gate for your dependencies, as a single static binary"
  homepage "https://tuxcare.com/securechain"
  version "0.1.4"
  # The TuxCare License Agreement has no SPDX identifier; brew's symbol for that.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://securechain.tuxcare.com/get/v0.1.4/securechain-darwin-arm64"
      sha256 "6ff6322da540c7bbad45c83b9c9eadeb9b77248f3fe144e0335cd5b24bf4af18"
    end
    on_intel do
      url "https://securechain.tuxcare.com/get/v0.1.4/securechain-darwin-amd64"
      sha256 "dc0ecb02dc713848f0fc0b3ee305f6e0f5875323b965ad7968875a2884eb56f0"
    end
  end

  on_linux do
    on_arm do
      url "https://securechain.tuxcare.com/get/v0.1.4/securechain-linux-arm64"
      sha256 "0883d04bd506db9d08b6fdf890fc1978faccfe1193bc3f906500b85aad32ce34"
    end
    on_intel do
      url "https://securechain.tuxcare.com/get/v0.1.4/securechain-linux-amd64"
      sha256 "cc84379864d0a0c3fb76950d383f70cbe4ec97e28194e5d5521844bab12a5aca"
    end
  end

  def install
    bin.install Dir["securechain-*"].fetch(0) => "securechain"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/securechain version")
  end
end
